feed-crawler/package-lock.json, feed-crawler/package.json, feed-crawler/src/common/mysql-access.ts, feed-crawler/src/container.ts, feed-crawler/src/feed-crawler.ts, feed-crawler/src/main.ts, feed-crawler/src/repository/feed.repository.ts, feed-crawler/src/repository/rss.repository.ts, feed-crawler/src/types/database-connection.ts, feed-crawler/src/types/dependency-symbols.ts
기존의 `runCrawler`라는 네이밍보다는 `main`이 어울린다 생각하여 함수 명을 변경하였습니다.
의존성 주입 방식을 위해서는 사용중인 Connection 객체들을 추상화 하여야 합니다.
이에따라 `DatabaseConnection` 인터페이스를 생성하고, 사용할 수 있도록 처리하였습니다.
- [**DI Container를 도입한 이유는 무엇인가요?**](https://f-lab.kr/insight/dependency-injection-and-di-container-20240802)
기존 코드는 의존성을 가지는 클래스가 생성되어 있는 인스턴스를 직접 import해 사용했습니다.
```typescript
import {mysqlConnection} from "../common/mysql-access";
export class FeedRepository {
public async insertFeeds(resultData: FeedDetail[]) {
const query = `
INSERT INTO feed (blog_id, created_at, title, path, thumbnail)
VALUES (?, ?, ?, ?, ?)
`;
const insertPromises = resultData.map(async (feed) => {
return mysqlConnection.executeQuery(query, [ // 강한 결합
feed.blogId,
feed.pubDate,
feed.title,
feed.link,
feed.imageUrl,
]);
});
```
이러한 모듈끼리의 강결합은 OOP의 …
=> ♻️ refactor: FeedCrawler OOP 적용

server/src/chat/chat.gateway.ts, server/src/chat/chat.module.ts, server/src/chat/chat.service.ts
- 기존의 chatgateway에는 여러 책임이 있었습니다.
- 소켓 연결 관리
- 메세지 이벤트 핸들링
- Redis에 메세지 저장
- 날짜가 바뀌었을 때 보낼 시스템 메세지 핸들링
- 클라이언트의 IP를 확인하고 이름 생성 혹은 저장된 이름 가져오기
- 채팅 내역 불러오기
- gateway는 소켓 연결 관리와 메세지 이벤트 핸들링, 2가지의 책임을 지도록 관심사를 분리했습니다.
- 이렇게 함으로써 기존 코드보다 유지보수와 확장에 이점을 가질 수 있다고 생각했습니다.
- 나중에 service 레이어도 비대해지면 Redis와 관련된 부분을 모두 추출하여, repository 계층으로 분리할 수 있을 것 같습니다.
- gateway 내부에서 비즈니스 로직을 모두 service 레이어로 추출
- service 레이어로 추출하면서 메서드 이름, 접근 제한자 종류를 조금씩 수정했습니다.
- ex) `emitMidnightMessage` 같은 메서드는 `handleDateMessage`로 수정, `getIp`는 클라이언트 이름 설정에만 쓰이기에 private 전환 등...
=> ♻️ refactor: chatgateway의 관심사 분리, 채팅 비즈니스 로직을 chatservice로 구현

server/src/rss/service/feed-crawler.service.ts, server/src/rss/service/rss.service.ts
함께 토론 해주신 @asn6878 @CodeVac513 감사드립니다!!
- Repository 파
- TypeORM 엔티티와 매핑하는 행위는 비즈니스 로직보다 DB와 더 밀접한 연관이 있다.
- Service 계층이 비대해지면 비즈니스 로직 파악이 어렵다.
- Service 파
- 예외 경우가 있을 수 있다. ex) "loadRssFeeds의 글 작성자(feed.blog)는 newRssAccept이다.' 라는 것을 DB 입장에서도 볼 수 있지만, 서비스 입장에서도 보면 작성자를 대입해주는 것이기에 비즈니스 로직이다.
- 레포지토리 계층은 간단하게 처리할 수록 재사용 가능성이 생긴다.
결론
1. GPT를 사용해서 답을 찾아도 GPT 가스라이팅 하면 그대로 답이 나오기 때문에 의미가 없다.
2. 그러므로 팀 내에서 결정한다.
3. 정답은 없고, 나중에 어떻게 될지 모르기 때문에 우선은 작업자의 선택에 따른다. -> Repository 계층에서 TypeORM 매핑, 전처리 수행
-   RSS 승인시 데이터 전처리 부분 Repository 계층으로 위임
=> ♻️ refactor: 데이터 전처리 Repository 계층으로 위임

feed-crawler/src/common/redis-access.ts, feed-crawler/src/container.ts, feed-crawler/src/repository/feed.repository.ts, feed-crawler/src/types/dependency-symbols.ts, server/src/admin/service/admin.service.ts, server/src/chat/service/chat.service.ts, server/src/common/guard/auth.guard.ts, server/src/common/redis/redis.service.ts, server/src/feed/scheduler/feed.scheduler.ts, server/src/feed/service/feed.service.ts, server/src/statistic/service/statistic.service.ts, server/test/admin/e2e/logout.e2e-spec.ts, server/test/feed/e2e/feedId.e2e-spec.ts, server/test/feed/e2e/recent.e2e-spec.ts, server/test/feed/e2e/trend.e2e-spec.ts, server/test/rss/e2e/accept.e2e-spec.ts, server/test/rss/e2e/history/accept.e2e-spec.ts, server/test/rss/e2e/history/reject.e2e-spec.ts, server/test/rss/e2e/reject.e2e-spec.ts, server/test/statistic/e2e/today.e2e-spec.ts
다른 부분과 동일하게 `RedisConnection` 인스턴스도 의존성 주입방식을 통해 관리하도록 처리 하였습니다.
재사용성이 낮을것으로 생각되어, **`DatabaseConnection`과 달리 `RedisConnection`은 별도의 인터페이스를 통해 추상화 하지 않았습니다.**
사용중이던 Redis 관련 메서드들을 메서드화 하였습니다. 대부분의 메서드 들은 실제 redis 객체에 접근해 사용하는 것과 큰 차이가 없도록 구현하였으나, 몇가지 특이사항 있는 부분들은 아래와 같습니다.
- **`scan()`**
`scan()` 메서드는 중복 데이터를 반환할 가능성이 있기에, **매 반복문 마다 필요한 데이터를 찾아 처리해주는 로직을 직접 작성하는 것이 옳다는 판단을 내렸습니다.**
- **`executePipeline()`**
`pipeline()` 메서드는 `ChainableCommander` 이라는 객체에 접근해 레디스 명령 함수들을 실행시키는 형태로 동작들을 수행하는데, 이때 ChainableCommander 내 함수들의 목록을 받도록 구현해야 완전한 캡슐화가 가능합니다.
하지만 이는 제겐 다소 복잡하게 느껴져 **`ChainableCommander`를 매개변수로 전달 해주고, 함수들의 모음인 콜백 함수만 받는 형태로 설계 하였습니다.**
- **그 외 실제 구현체와 차이점**
실제 구현체에서는 대부분의 key값이나 데이터들을 `string | number | Buffer` 형태로 다양한 타입을 지원합니다. 하지만 본 PR의 커스텀 구현체에서 `Buffer`는 사용할일이 없다고 판단해 별도로 지원하지 …
=> ♻️ refactor: Redis 동작 메서드 캡슐화

client/.gitignore, client/src/components/chart/BarChartItem.tsx, client/src/components/chat/ChatItem.tsx, client/src/hooks/queries/useSearch.ts
-  sonarqube를 사용하면서 커밋에 필요없는 파일이 추가되어서 넣었습니다.
-  타입에 들어갈 boolean을 Boolean으로 적은 코드가 있었고
- 반복문에 const of가 아니라 let of를 사용한 코드가 있어서 수정했습니다.
-   소소한 코드정리
=> ♻️ refactor: 소소한 코드정리

feed-crawler/src/repository/feed.repository.ts, server/src/admin/controller/admin.controller.ts, server/src/admin/dto/request/login-admin.dto.ts, server/src/admin/dto/request/register-admin.dto.ts, server/src/feed/api-docs/searchFeedList.api-docs.ts, server/src/feed/api-docs/updateFeedViewCount.api-docs.ts, server/src/feed/controller/feed.controller.ts, server/src/feed/dto/request/feed-update.dto.ts, server/src/feed/dto/response/feed-pagination.dto.ts, server/src/feed/service/feed.service.ts, server/src/main.ts, server/src/rss/controller/rss.controller.ts, server/src/rss/dto/request/rss-register.dto.ts, server/src/rss/service/rss.service.ts, server/src/statistic/controller/statistic.controller.ts, server/src/statistic/service/statistic.service.ts, server/test/feed/e2e/trend.e2e-spec.ts, server/test/jest.setup.ts, server/test/rss/e2e/history/accept.e2e-spec.ts, server/test/rss/e2e/history/reject.e2e-spec.ts, server/test/statistic/e2e/all.e2e-spec.ts, server/test/statistic/e2e/today.e2e-spec.ts
-   Redis에 어느 정도의 데이터가 저장되어있는 지 애플리케이션 단에서 미리 파악할 수 없다.
- JS의 최대 숫자 범위를 벗어나버리면 서비스 예외가 발생한다.
- JS의 최대 숫자 범위 9007199254740991 만큼 개수 범위가 크지는 않겠지만 시스템 안정성을 위해 문자열로 반환하도록 처리 
1. Repository 함수 재사용하게 변경
2. Swagger 처리 부분 변경
- Swagger Request Example `api-docs.ts` -> `DTO`로 변경
- 작업 사유: 현재 새로운 API 생성시 api-docs.ts에 수동으로 API Request DTO의 속성들을 등록하는 몇몇 부분들이 있음. Request DTO를 생성할 때, ApiProperty를 사용해서 자동으로 연동되도록 하는 게 편할듯 함
- Swagger Response Example `DTO`로 변경 하능 하다면 변경
- 작업 사유: 위와 동일
- 코드는 여러 명이 적었다 한들 하나의 프로젝트 내부라면 코드 형식이 모두 동일해야 한다고 판단했다.
- 추상적으로 작성되어 있는 코드들이 많아 다시 코드를 읽을 때 이해 안 되는 부분이 상당히 많았다.
- 눈에 거슬리는 코드도 너무 많았기에 작업을 수행했다.
- 정규 프로젝트 기간에는 마감 일자로 인해 촉박해져 막 작업한 부분이 꽤 많았다.
- 파라미터 DTO 적용 하여 값 검증하게 변경
- 특정 코드는 파라미터를 직접 추출하는 방식이라 값 검증이 안 되는 문제가 있었음. 코드 통일성을 위해 DTO 추가
```typescript
@Params('feedId') params: …
```
=> 🧼 clean: 코드 일관성 향상

server/package-lock.json, server/package.json, server/src/admin/controller/admin.controller.ts, server/src/admin/dto/request/login-admin.dto.ts, server/src/admin/dto/request/register-admin.dto.ts, server/src/admin/repository/admin.repository.ts, server/src/admin/service/admin.service.ts, server/src/feed/controller/feed.controller.ts, server/src/feed/service/feed.service.ts, server/src/rss/controller/rss.controller.ts, server/src/rss/service/rss.service.ts, server/src/statistic/controller/statistic.controller.ts, server/src/statistic/service/statistic.service.ts, server/test/admin/dto/login-admin.dto.spec.ts, server/test/admin/dto/register-admin.dto.spec.ts, server/test/admin/e2e/login.e2e-spec.ts, server/test/admin/e2e/register.e2e-spec.ts, server/test/admin/e2e/sessionId.e2e-spec.ts, server/test/fixture/admin.fixture.ts
-   테스트를 마지막쯤에 작성해서 너무 막 적은 감이 있었다.
- Admin 도메인에 대해 적용해보고 팀원들이 동의할 경우 다른 도메인에도 적용할 계획이다. PR 룰 (추가, 삭제 400줄 이내)를 지키기 위해 Admin 도메인에만 사전 적용한다.
- Admin 테스트 픽스처를 활용하지 않고 있었다.
- Admin 도메인의 테스트 사전 단계(beforeAll)에서 서비스 계층으로 테스트 데이터를 삽입하던 부분을 Repository 계층에서 바로 삽입하게 바꿨다.
-  feed 도메인 작업 https://github.com/boostcampwm-2024/refactor-web05-Denamu/pull/15
-  rss 도메인 작업 https://github.com/boostcampwm-2024/refactor-web05-Denamu/pull/17
- statistic 도메인 작업 https://github.com/boostcampwm-2024/refactor-web05-Denamu/pull/18
- 비밀번호를 암호화한 걸 들고 있을 이유가 없다.
- 매번 사용할 때마다 암호화한 결과를 개발자가 알고 있어야 하는데, 상당히 번거롭다. 서비스에 실제로 대입을 해봐야한다. 그렇기에 비밀번호 평문을 넣을때 암호화되게 하여 사용성을 높였다.
- 해싱 횟수 10회나 1회나 실제로 동작하는 시간은 별 차이 없었지만, 이론상 더 빠를 것으로 판단하여 기존 서비스에서는 10번 해싱을 1번 해싱으로 최적화 했다. (1 Core 2GB, 8 Core 32GB 환경에서 수행시 1회나 10회 동일함을 확인)
- DTO를 사용해야 …
=> ♻️ refactor: admin 도메인 repository 함수 재사용성 향상, 테스트 코드 일관성, 최적화

server/src/feed/dto/request/feed-pagination.dto.ts, server/src/feed/dto/request/feed-update.dto.ts, server/src/feed/repository/feed.repository.ts, server/src/feed/service/feed.service.ts, server/test/feed/dto/feed-pagination.dto.spec.ts, server/test/feed/dto/feed-update.dto.spec.ts, server/test/feed/e2e/feed.e2e-spec.ts, server/test/feed/e2e/feedId.e2e-spec.ts, server/test/feed/e2e/trend.e2e-spec.ts
-   어느 한 타입으로 지정해두면 Repository 계층 함수를 재사용할 수 없다.
- Repository 계층에 있는 함수를 재사용할 일이 있으려나 싶긴 하지만, 혹시나 하는 마음에 작업한다. 
- Select 함수들은 DTO가 아닌 개별 인자값으로 받게 하고, INSERT 하는 부분들은 DTO에서 Entity로 바꿔 삽입할 수 있도록 한다. 그러기 위해서는 전처리 작업 했던 부분을 롤백해야 한다.
-   feed 도메인 Repository 계층 함수들 단일 인자 값으로 변경
- feed 도메인 DTO 생성자 추가
- feed 도메인 조회수 증가 DTO 테스트 코드 작성
- typeorm save -> insert로 변경하여 성능 개선
=> ♻️ refactor: feed 도메인 repository 함수 재사용성 향상, 테스트 코드 일관성, 최적화

server/src/rss/dto/request/rss-management.dto.ts, server/src/rss/dto/request/rss-register.dto.ts, server/src/rss/dto/request/rss-reject.dto.ts, server/src/rss/repository/rss.repository.ts, server/src/rss/service/feed-crawler.service.ts, server/src/rss/service/rss.service.ts, server/test/rss/dto/rss-management.dto.spec.ts, server/test/rss/e2e/accept.e2e-spec.ts, server/test/rss/e2e/history/accept.e2e-spec.ts, server/test/rss/e2e/history/reject.e2e-spec.ts, server/test/rss/e2e/reject.e2e-spec.ts, server/test/rss/e2e/rss.e2e-spec.ts
1. SELECT 쿼리를 통해 엔티티 객체에 정의된 PK를 사용하여 DB 내 엔티티 존재 여부를 확인한다.
2. 없을 경우 INSERT를 수행한다.
3. 있을 경우 UPDATE를 수행한다.
4. 변경 또는 삽입된 데이터를 SELECT로 조회해서 엔티티로 반환한다.
1. 냅다 넣는다.
2. 메타 정보만 반환한다.
결론: insert가 성능이 빠르다. 다만, 반환되어야 하는 엔티티가 필요하다면 save를 사용해야 한다.
- 다른 DTO들은 전부 생성자로 구현되어 있는데, RssRegisterRequestDto만 from 함수가 존재했다.
- 테스트 코드 때문에 원본 코드에 테스트를 위한 특수 함수가 존재하는 건 오히려 원본 코드에 혼란을 주는 느낌이 들었다. 어디서 사용했는지 사용처를 알아야 하는데, 테스트에 있는 게 이상하다고 판단했다.
-   typeorm save -> insert로 변경하여 성능 개선
- 테스트 코드 픽스처 라인 정리
- from 함수 제거
- 필요없는 return 제거
- rss 도메인 repository 재사용 가능하도록 개별 변수 인자로 변경
=> ♻️ refactor: rss 도메인 repository 함수 재사용성 향상, 테스트 코드 일관성, 최적화

client/src/api/services/rss.ts, client/src/components/RssRegistration/RssUrlInput.tsx, client/src/components/admin/layout/AdminMember.tsx, client/src/components/chart/PieChartItem.tsx, client/src/components/chat/ChatButton.tsx, client/src/components/chat/ChatItem.tsx, client/src/components/chat/layout/ChatFooter.tsx, client/src/components/chat/layout/ChatSection.tsx, client/src/components/layout/Header.tsx, client/src/components/layout/SideButton.tsx, client/src/components/search/SearchButton.tsx, client/src/components/search/SearchFilters/FilterButton.tsx, client/src/components/search/SearchHigilight.tsx, client/src/components/search/SearchResults/SearchResultList.tsx, client/src/hooks/queries/useInfiniteScrollQuery.ts, client/src/hooks/queries/useSearch.ts, client/src/store/useChatStore.ts
-   초기 104개가 있던 이슈를 34개 까지 줄임
-   남아있는 이슈들은 map함수에서 배열 index의 사용이나 modal컴포넌트의 div에 달린 onClick이벤트 때문입니다
-    실패가 뜬 이유는 테스트 커버리지를 80%로 잡았는데 현재 0%가 나와서 실패한것입니다
=> ♻️ refactor: sonarQube에 나온 이슈 해결

feed-crawler/package-lock.json, feed-crawler/package.json, feed-crawler/src/common/redis-access.ts, feed-crawler/src/common/sqlite-access.ts, feed-crawler/src/repository/feed.repository.ts
- 기존에는 Nest 혹은 TypeORM에서 DI, DB DDL 등 여러 편의성을 제공했습니다.
- DB DDL 작성은 constructor에서 하드 코딩하여 일단은 해결했습니다.
- DI는 Tsyringe를 사용하여 처리할 예정입니다.
- iordies-mock 의존성 추가 및 테스트 환경에서는 ioredis-mock을 사용하도록 수정
- better-sqlite3 의존성 추가
- feedRepository 로그 메시지에 SQLite 추가
- sqlite-access.ts 작성
- 일단 클로드에게 간단한 test 코드 작성을 부탁해서 세팅이 제대로 동작하는지 확인했습니다.
=> ✅ test: Test환경에서 SQLite를 사용할 수 있도록 코드 추가 및 기존 코드 수정

client/src/components/chat/ChatButton.tsx, client/src/components/chat/layout/ChatFooter.tsx, client/src/components/chat/layout/ChatSection.tsx, client/src/components/layout/Header.tsx, client/src/components/layout/Sidebar.tsx, client/src/components/layout/navigation/DesktopNavigation.tsx, client/src/components/layout/navigation/MobileNavigation.tsx, client/src/components/search/SearchButton.tsx, client/src/components/search/searchPages/SearchPages.tsx, client/src/components/ui/pagination.tsx, client/src/components/ui/sheet.tsx, client/src/components/ui/sidebar.tsx, client/src/hooks/common/useMediaQuery.ts, client/src/store/useSidebarStore.ts
```
import { useState, useEffect } from "react";
export const useMediaQuery = (query: string): boolean => {
const [viewport, setViewport] = useState(false);
useEffect(() => {
const mediaQuery = window.matchMedia(query);
setViewport(mediaQuery.matches);
const eventListener = (e: MediaQueryListEvent) => {
setViewport(e.matches);
};
mediaQuery.addEventListener("change", eventListener);
return () => {
mediaQuery.removeEventListener("change", eventListener);
};
}, [query]);
return viewport;
};
```
- 문자열로 입력받은 viewport의 크기를 useEffect를 이용해 확인해가면서 모바일인지 아닌지 판단하는 함수입니다.
-   헤더 반응형
-   채팅 및 사이드바 반응형
-   검색시 페이지네이션 부분 반응형
- 모바일일 경우 헤더의 로고부분을 변경하고 사이드바가 나올 수 있는 햄버거버튼을 추가했습니다.
- 페이지네이션시 previous, next라는 글자로 버튼을 생성했었는데 모바일에서는 글자가 잘리는 문제가 발생해서 삭제시켰습니다.
- 사이드바와 채팅 모두 화면을 꽉 채우게 변경시켰습니다.
=> ♻️ refactor: 채팅, 헤더 반응형 작업

client/src/App.tsx, client/src/components/common/Card/PostCard.tsx, client/src/components/common/Card/PostCardContent.tsx, client/src/components/common/Card/PostCardImage.tsx, client/src/components/common/SectionHeader.tsx, client/src/components/layout/Header.tsx, client/src/components/layout/Layout.tsx, client/src/components/sections/AnimatedPostGrid.tsx, client/src/components/sections/LatestSection.tsx, client/src/components/sections/MainContent.tsx, client/src/components/sections/TrendingSection.tsx, client/src/components/ui/card.tsx, client/src/store/useMediaStore.ts, client/src/types/card.ts, client/src/types/post.ts
- 반응형 레이아웃 변경
- 모바일 카드 디자인 수정
- 반응형 레이아웃 변경
- useMediaQuery 훅 생성 후 해당 훅으로 viewport의 크기를 판단하여 모바일인지 데스크탑인지 판단하도록 작성했습니다.
- useMediaStore  스토어를 생성하여 각 컴포넌트 별로 뷰포트의 크기를 계산하는게 아니라 app.tsx가 마운트 될 때 검사를 진 
행하도록 구현했습니다.
- layout과 pages폴더의 스타일을 수정하여 768px 미만일 때만 구조가 변경되도록 수정했습니다.
- 모바일 카드 디자인 수정
- 이전에 피그마로 보여드린 디자인대로 수정해봤습니다.
=> ♻️ refactor: 반응형 레이아웃 변경, 모바일 카드 디자인 수정

server/src/feed/entity/feed.entity.ts, server/src/feed/entity/tag-map.entity.ts, server/src/feed/module/feed.module.ts, server/src/feed/repository/tag-map.repository.ts
명기님께서 의견을 주셨고 저와 명기님, 민석님이 함께 합의를 보았습니다.
클로바 스튜디오 API를 사용할 때는 원하지 않던 데이터가 함께 추출되어 저희가 원하는 태그만 사용할 수 있도록 Tag 테이블을 생성했습니다. 
그러나 Claude API로 변경 후에는 개발자가 제시한 프롬프트 내에서 데이터가 추출되어 Tag 테이블이 필요하지 않다는 의견이 있었습니다.  
Tag 데이터가 갱신되지 않고 읽는 용으로만 사용되어, AI 모델의 정확성이 높다면 프롬프트를 통해서만 관리할 수 있습니다.
굳이 테이블을 하나 더 관리하고 Join 연산을 추가할 필요가 없었고 납득이 되어 이대로 진행했습니다.
- TagMap 엔티티 생성
- Feed 엔티티에 Tag 배열과 summary 추가
=> ✨ feat: Tag-Map Entity 추가

feed-crawler/src/common/constant.ts, server/src/rss/service/ai-tag-summary.service.ts
-  요약 첫 줄이 h1 태그인 경우가 있고, bold인 경우가 있고, 일반적인 경우가 있어서 불편함 가독성 떨어짐!
- Enginnering이라는 태그 범위가 너무 넓어서 앵간한 게시글에 싹 다 Enginnering 태그가 붙음. Engineering을 Software Engineering으로 바꾸기에는 너무 김. 그래서 없애기로 결정!
-   프롬프트 정확성 추가. 요약 글 제목에는 반드시 bold체 + 요약 제목을 적도록 프롬프트 추가
=> 🐛 fix: 요약 글 제목 및 bold체로 출력되게 구현

feed-crawler/src/common/constant.ts, server/src/rss/service/ai-tag-summary.service.ts
https://github.com/boostcampwm-2024/refactor-web05-Denamu/pull/49
enginnering 태그 삭제
=> 🐛 fix: engineering 태그 너무 포괄적 범주라 삭제

client/src/components/common/Card/detail/PostContent.tsx, client/src/pages/PostDetailPage.tsx
detail 페이지에서 요악이 없을 경우 발생하는 에러 수정
-   삼항연산자 이용해서 없는경우 빈 문자열이 들어가도록 수정
-   요약이 없으면 인공지능이 요약한 내용이라고 안나오게 수정
=> 🐛 fix: detail페이지에서 요악이 없을 경우 발생하는 에러 수정

.gitignore, client/.dockerignore, client/.gitignore, client/Dockerfile, client/docker/Dockerfile.dev, client/docker/Dockerfile.local, client/vite.config.ts, nginx/nginx.conf, nginx/scripts/generate_cert.sh
- 1편: https://github.com/boostcampwm-2024/refactor-web05-Denamu/pull/35
- 우리 팀에 필요한 Docker 환경은 무엇이 있을까?
1. 개발 환경
2. 로컬 환경 (포트폴리오)
3. 운영 환경
개발 환경 먼저 설정을 하려 했으나, 백엔드측 feed-crawler에서 환경 변수 문제로 인해 Docker CI/CD도 함께 공부하면서 진행해야 할듯 하여 일단은 프론트엔드 코드 먼저 이미지로 변경 하는 PR 작성
Host OS와 NGINX Conf를 동기화하기 위해서는 Volume을 이용해야 하는데, 단일 Dockerfile에서 HostOS와 볼륨을 연결하는 방법은 없고 Docker Compose를 사용해야 한다. Docker Compose PR은 서버까지 다 끝내고 올리도록 하겠습니다.
- 빌드 시간
- 용량
docker build client -t denamu-front
빌드 15초, 용량 1.51 GB
```dockerfile
FROM node:22
WORKDIR /var/client
COPY . .
RUN npm ci
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
```
일반 리눅스 배포판보다 크기가 작은 alpine 버전을 사용하도록 변경하여 베이스 이미지 크기 줄이기
빌드 15초, 용량: 572 MB
- 빌드 시간
- 용량
```dockerfile
FROM node:22-alpine
WORKDIR /var/client
COPY . .
RUN npm ci
CMD ["npm", "run", "dev", …
```
=> 📦 chore: 프론트엔드 Docker 이미지 작성 개발 환경, 로컬 환경 Docker Compose (2)

feed-crawler/.dockerignore, feed-crawler/docker/Dockerfile.dev, feed-crawler/docker/Dockerfile.local
- 1편: https://github.com/boostcampwm-2024/refactor-web05-Denamu/pull/35
- 2편: https://github.com/boostcampwm-2024/refactor-web05-Denamu/pull/34
-   크론은 데몬 프로세스라 포어그라운드로 돌아가는 프로세스가 아니라서 Docker에서 인식을 하지 못 하고 컨테이너가 꺼지는 문제가 발생했다.
- 크론은 데몬 프로세스이기에 출력 결과가 터미널로 넘어오지 않는 문제가 있었다.
- 중간 파일을 두어, tail 을 통해 파일 변화를 탐지하고 그 결과를 출력하도록 변경했다.
alpine 버전은 여타 다른 리눅스 배포판과 다르게 Bash가 아닌 ash를 사용한다. 그래서 표준 오류와 표준 출력을 함께 쓰는 리다이렉트 문법인 `&>>` 은 사용할 수 없다.
표준 에러와 표준 출력을 2&>1 로 적어줘야 올바르게 파일로 출력 내용이 리다이렉트 되었다.
- Feed Crawler Dev 이미지 Dockerfile 작성 
-   Feed Crawler Local 이미지 Dockerfile 작성
=> 📦 chore: Feed Crawler Docker 이미지 작성 개발 환경, 로컬 환경 Docker Compose (3)

.github/workflows/deploy_client.yml, .github/workflows/deploy_feed-crawler.yml, .github/workflows/deploy_server.yml
보안 향상을 위한 단일 진입점 (NGINX)를  제외한 모든 리소스들을 Private 으로 옮기자는 의사결정이 진행됨.
**인프라 구성이 변경되었습니다.** [(디테일한 패스워드나 주소와 같은 내용들은 노션 프라이빗 문서 참고해주세요.)](https://www.notion.so/DB-64048d5ecfcd4b09a64faca1825b125b?pvs=4)
- VPC 
- Public Subnet / Public Server (1Core 1GB)
- NGINX
- Static Files (FE build files, Static images.... etc)
- Private Subnet / Private Server (2Core 4GB)
- WAS
- Redis
- MySQL
비용 문제로 인해 NAT를 유지하기 않기로 결정됨에 따라 SCP를 사용한 파일 전달의 필요성 대두.
그리하여 `feed-crawler`, `server`, `client`의 CI/CD 스크립트가 변경되었습니다.
별도의 의존성 설치후 프라이빗 서버로 전달이 필요한 `feed-crawler`, `server` 같은 경우는 다음과 같은 흐름으로 작업을 수행합니다.
> `git pull` -> `npm ci` -> `프로젝트 압축` ->`scp 를 사용한 압축 파일 전송` -> `ssh proxy 접속` -> `압축 해제` -> `npm run build` -> `pm2 restart`
Public Server가 비교적 저렴한 사양의 인스턴스를 사용하게 될 것을 고려해 **빌드는 Private 인스턴스에서 실행하도록 처리** 하였습니다.
아래 …
=> 🐛 fix: 배포 스크립트 배포 로직 변경

feed-crawler/test/jest-e2e.json, feed-crawler/test/jest-integration.json, feed-crawler/test/jest-unit.json, server/test/jest-e2e.json, server/test/jest-integration.json, server/test/jest-unit.json
사양이 낮은 컴퓨터(ex. github cicd server, 노트북 등)에서 Docker를 이용하여 임시 컨테이너 만드는 테스트 코드가 사양 문제로 인해 느리게 수행되는 문제가 있었다.
github ci/cd server에서 테스트 실패가 뜰 경우 re-run job을 수행해야 해서 생산성이 저하됐다.
-   jest time out 설정 (default 5,000ms -> 10,000ms)
=> 📦 chore: jest timeout docker 시간 설정

.github/workflows/deploy_feed-crawler.yml, .github/workflows/deploy_server.yml, feed-crawler/src/common/mysql-access.ts
마지막 Feed Crawler에서 AI Queue를 사용하도록 한 부분에서 환경변수 AI_RATE_LIMIT_COUNT가 추가 되었는데, 추가를 안 했습니다. 죄송합니다 ㅠ.ㅠ
발표 전이라 조금 리스크는 있겠지만, 환경변수 이름 한 가지를 바꿨습니다. 확실하게 바꿔놨습니다!
- Feed Crawler 확인해보니 환경변수 명이 PORT -> DB_PORT로 바뀌어야 했음. 그래서 바꿈
- Feed Crawler에 AI_RATE_LIMIT_COUNT 환경변수 추가
-   사용하지 않는 환경 변수 15개 가량 Github Repository에서 제거
ex) RSS_NOTIFIER_*, HOST, PORT, SSH_KEY, SSH_PRIVATE_INSTANCE_KEY, USERNAME 등등... 안 쓰이는 것들 제거함
=> [긴급] 🐛 fix: CI/CD 버그 수정 및 사용되지 않는 환경 변수 제거
